// src/views/ContactsView.jsx
// src/views/ContactsView.jsx
import React from 'react';
import { FaLinkedin, FaGithub, FaAt } from 'react-icons/fa';
import FancyButton from '@/components/elements/FancyButton.jsx';
import AnimatedText from "@/components/elements/AnimatedText.jsx";

export default function ContactsView() {
  return (
      <main className="flex-grow flex flex-col items-center justify-start">
          <AnimatedText
              text="Contacts"
              className="text-4xl py-12 px-4 font-bold"
              delay={60}
              duration={0.4}
              splitType="chars"
          />

        <div className="mt-24 flex flex-wrap justify-center gap-6 px-4">
          {/* LinkedIn */}
          <FancyButton
              icon={FaLinkedin}
              text="LinkedIn"
              href="https://linkedin.com/in/simone-cotardo"
              color="#0A66C2"
          />

          {/* GitHub */}
          <FancyButton
              icon={FaGithub}
              text="GitHub"
              href="https://github.com/whyorwhat"
              color="#333333"
          />

          {/* Email */}
          <FancyButton
              icon={FaAt}
              text="Send Email"
              href="mailto:simo.cotardo@gmail.com"
              color="#059669"
          />
        </div>
      </main>
  );
}

// src/views/ContactsView.vue
<template>
  <div class="layout">
    <header>
      <Navbar />
    </header>
    <main class="content">
      <h1 class="page-title">Contacts</h1>
      <div class="button-container">
        <a
            class="custom-btn"
            href="https://linkedin.com/in/simone-cotardo"
            target="_blank"
            rel="noopener noreferrer"
        >
          <font-awesome-icon :icon="['fab', 'linkedin']" /> LinkedIn
        </a>
        <a
            class="custom-btn"
            href="https://github.com/whyorwhat"
            target="_blank"
            rel="noopener noreferrer"
        >
          <font-awesome-icon :icon="['fab', 'github']" /> GitHub
        </a>
        <a
            class="custom-btn"
            href="mailto:simo.cotardo@gmail.com"
        >
          <font-awesome-icon :icon="['fas', 'at']" /> Send Email
        </a>
      </div>
    </main>
    <Footer />
  </div>
</template>

<script>
import Navbar from "@/components/Navbar.vue";
import Footer from "@/components/Footer.vue";

export default {
  name: "ContactView",
  components: {
    Navbar,
    Footer,
  },
};
</script>

<style scoped>
.layout {
  min-height: 100vh;  /* Min page size */

  display: flex;
  flex-direction: column;
}

header {
  flex-shrink: 0; /* Fixed header */
}

.content {
  flex-grow: 1; /* Content can expand */
  display: flex;
  flex-direction: column;
  align-items: center; /* Buttons vertically centered */
  justify-content: center; /* Buttons horizontally centered */
  padding: 20px;
}

.button-container {
  display: flex;
  flex-direction: column; /* Vertical positioning */
  gap: 15px;
}
.page-title {
  font-size: 3rem;
  font-weight: bold;
  text-align: center;
  margin-bottom: 30px;
}
</style>
