// src/views/ProjectsView.vue
<template>
  <div class="layout">
    <Navbar />
    <div class="container mt-5">
      <h1 class="page-title">My Projects</h1>
      <ProjectsSection />
    </div>
    <Footer />
  </div>
</template>

<script>
import Navbar from '../components/Navbar.vue';
import ProjectsSection from '../components/ProjectsSection.vue';
import Footer from '../components/Footer.vue';

export default {
  name: 'ProjectsView',
  components: {
    Navbar,
    ProjectsSection,
    Footer,
  },
};
</script>

<style scoped>
.layout {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}
.container {
  flex-grow: 1;
  padding-bottom: 50px;
}
.page-title {
  font-size: 3rem;
  font-weight: bold;
  text-align: center;
  margin-bottom: 30px;
}
</style>

// src/views/ProjectsView.jsx
import React from 'react';
import {ProjectsSection} from "@/components/projects/ProjectsSection.jsx";
import AnimatedText from "@/components/elements/AnimatedText.jsx";

export default function ProjectsView() {
  return (
      <div className="flex flex-col min-h-screen font-sans bg-white">
        <main className="flex-grow container mx-auto px-4 py-12">
            <div className="text-center">
                <AnimatedText
                    text="Projects"
                    className="text-4xl mb-10 font-bold text-center"
                    delay={60}
                    duration={0.4}
                    splitType="chars"
                />
            </div>

          <ProjectsSection />
        </main>
      </div>
  );
}
