// src/views/TiSeguoView.vue
<template>
  <div class="container d-flex align-items-center justify-content-center vh-100">
    <div class="card shadow-lg p-4 text-center" style="max-width: 600px; width: 100%;">
      <div class="card-body">
        <h1 class="card-title mb-3">TiSeguo</h1>
        <p class="card-text text-muted mb-4">
          The presentation page of the project is currently under development. Check back soon!
        </p>
        <router-link to="/projects" class="btn btn-primary">
          Back to other projects
        </router-link>
      </div>
    </div>
  </div>
</template>

<style scoped>
.container {
  background-color: #f8f9fa;
}
.card {
  border-radius: 12px;
}
</style>

// src/views/projects/TiSeguoView.jsx
import { FaArrowLeft } from 'react-icons/fa';
import FancyButton from '@/components/elements/FancyButton.jsx';

export default function TiSeguoView() {
  return (
        <main className="flex-grow flex items-center justify-center px-4 py-12">
          <div className="bg-white border border-gray-300 shadow-lg p-6 rounded-lg max-w-lg w-full text-center">
            <h1 className="text-3xl font-bold mb-3">TiSeguo</h1>
            <p className="text-gray-500 mb-6">
              The presentation page of the project is currently under development. Check back soon!
            </p>
            <FancyButton
                icon={FaArrowLeft}
                text="Back to other projects"
                to="/projects"
                color="#2563eb"
            />
          </div>
        </main>
  );
}
